### ISSUE TITLE
Function Keys No longer Working(F1 - F12)

### ISSUE THREAD

**Issue by mhenr014** [linsight/react-keyboard-event-handler#4]
Love the lib, currently I am heavily dependent on the function keys working with this library.  In version 1.3.1.  I had no issues whatsoever, it appears that keys outside of your alias are mapped to 'other' and should fall under the alias 'all' . However, as of 1.3.2 my keys are no longer being detected, stepping into the code, I can see alphanumeric and numeric are still registering, but no longer function keys F1 etc.. Please take a look when you can and let me know if something in my code needs to change to handle the update. Once again, thank you for a wonderful lib!

**Comment by dlin-me** [comment]
Hi, I will add supports to it today.

**Comment by dlin-me** [comment]
Hi @mhenr014 , thanks for reporting the issue. A new version 1.40 is out with support for Fn keys.

A bug has also been fixed in 'all' alias keys. The fix allows you to use the second parameter (raw event object) to handles keys that are not defined in the supported key name table. 

Please let me know if you find any other issues. Cheers.

**Comment by dlin-me** [comment]
closing issue now. Will reopen if there are more issues.
